version: "3.9"

services:
  app:
    container_name: app
    environment:
      SPRING_PROFILES_ACTIVE: local
    build:
      context: .
      dockerfile: DockerfileJdk
    ports:
      - "8081:8080"
    volumes:
      - /Users/bj/docker/app:/app
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: app-db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - /Users/bj/docker/db:/var/lib/mysql


