api:
  prefix: /api

spring:
  profiles:
    default: local
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
