apiVersion: v1
kind: Service
metadata:
  name: app-example
  labels:
    app: app-example
spec:
    ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
    selector:
        app: app-example
    type: LoadBalancer
